apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linetime-backend
  name: linetime-backend
  namespace: linetime
spec:
  selector:
    matchLabels:
      app: linetime-backend
  template:
    metadata:
      labels:
        app: linetime-backend
    spec:
      containers:
      - image: linetime-backend
        imagePullPolicy: Never
        name: linetime-backend
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
             secretKeyRef:
                name: postgres-secret
                key: myDbPassword
        - name: SPRING_DATASOURCE_USERNAME
          value: "linetime_user"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/linetime_db"
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
