apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: linetime-backend
  name: linetime-backend
  namespace: linetime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linetime-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: linetime-backend
    spec:
      containers:
      - image: linetime-backend
        imagePullPolicy: Never #get image from local ones
        name: linetime-backend
        resources: {}
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
             secretKeyRef:
                name: postgres-secret
                key: myDbPassword
        - name: SPRING_DATASOURCE_USERNAME
          value: "linetime_user"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/linetime_db"


status: {}
