apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: linetime
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
  myDbPassword: postgresDbPsw
